package com.blog.bzl.myblog.model.dataobj;

import com.blog.bzl.myblog.model.baseobj.BaseModel;

public class User extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.home_url
     *
     * @mbg.generated
     */
    private String homeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.screen_name
     *
     * @mbg.generated
     */
    private String screenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.created
     *
     * @mbg.generated
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.activated
     *
     * @mbg.generated
     */
    private Integer activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.logged
     *
     * @mbg.generated
     */
    private Integer logged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myblog_user.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.id
     *
     * @return the value of myblog_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.id
     *
     * @param id the value for myblog_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.user_name
     *
     * @return the value of myblog_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.user_name
     *
     * @param userName the value for myblog_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.password
     *
     * @return the value of myblog_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.password
     *
     * @param password the value for myblog_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.email
     *
     * @return the value of myblog_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.email
     *
     * @param email the value for myblog_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.home_url
     *
     * @return the value of myblog_user.home_url
     *
     * @mbg.generated
     */
    public String getHomeUrl() {
        return homeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.home_url
     *
     * @param homeUrl the value for myblog_user.home_url
     *
     * @mbg.generated
     */
    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl == null ? null : homeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.screen_name
     *
     * @return the value of myblog_user.screen_name
     *
     * @mbg.generated
     */
    public String getScreenName() {
        return screenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.screen_name
     *
     * @param screenName the value for myblog_user.screen_name
     *
     * @mbg.generated
     */
    public void setScreenName(String screenName) {
        this.screenName = screenName == null ? null : screenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.created
     *
     * @return the value of myblog_user.created
     *
     * @mbg.generated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.created
     *
     * @param created the value for myblog_user.created
     *
     * @mbg.generated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.activated
     *
     * @return the value of myblog_user.activated
     *
     * @mbg.generated
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.activated
     *
     * @param activated the value for myblog_user.activated
     *
     * @mbg.generated
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.logged
     *
     * @return the value of myblog_user.logged
     *
     * @mbg.generated
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.logged
     *
     * @param logged the value for myblog_user.logged
     *
     * @mbg.generated
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myblog_user.group_name
     *
     * @return the value of myblog_user.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myblog_user.group_name
     *
     * @param groupName the value for myblog_user.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }
}